<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="iLoveVS._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

   



    <div style="margin: 5%; background-color:white;border-radius:25px; text-align:center;box-shadow: rgb(238, 36, 60, 0.4) 0px 0px 0px 3px, rgb(238, 36, 60, 0.3) 0px 0px 0px 6px, rgb(238, 36, 60, 0.2) 0px 0px 0px 9px, rgb(238, 36, 60, 0.1) 0px 0px 0px 12px, rgb(238, 36, 60, 0.05) 0px 0px 0px 15px;" >
        <asp:Image ID="Image1" runat="server" ImageUrl="~/Image/Background2.png" Width="80%" />
        <div style="padding: 25px; margin: 25px ; border-radius:25px;box-shadow: rgba(17, 17, 26, 0.1) 0px 4px 16px, rgba(17, 17, 26, 0.1) 0px 8px 24px, rgba(17, 17, 26, 0.1) 0px 16px 56px;">
            <div>
            <h1 class="font-sans w-full tracking-tighter lg:pb-6 pb-3 w-full -ml-0.5 2xl:text-6xl xl:text-5xl lg:text-4xl text-2xl text-black uppercase font-900" style="padding: 25px; box-sizing: border-box; border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); --tw-border-opacity: 1; --tw-ring-inset: var(--tw-empty, ); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 transparent; --tw-ring-shadow: 0 0 transparent; --tw-shadow: 0 0 transparent; --tw-blur: var(--tw-empty, ); --tw-brightness: var(--tw-empty, ); --tw-contrast: var(--tw-empty, ); --tw-grayscale: var(--tw-empty, ); --tw-hue-rotate: var(--tw-empty, ); --tw-invert: var(--tw-empty, ); --tw-saturate: var(--tw-empty, ); --tw-sepia: var(--tw-empty, ); --tw-drop-shadow: var(--tw-empty, ); --tw-filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow); --tw-backdrop-blur: var(--tw-empty, ); --tw-backdrop-brightness: var(--tw-empty, ); --tw-backdrop-contrast: var(--tw-empty, ); --tw-backdrop-grayscale: var(--tw-empty, ); --tw-backdrop-hue-rotate: var(--tw-empty, ); --tw-backdrop-invert: var(--tw-empty, ); --tw-backdrop-opacity: var(--tw-empty, ); --tw-backdrop-saturate: var(--tw-empty, ); --tw-backdrop-sepia: var(--tw-empty, ); --tw-backdrop-filter: var(--tw-backdrop-blur) var(--tw-backdrop-brightness) var(--tw-backdrop-contrast) var(--tw-backdrop-grayscale) var(--tw-backdrop-hue-rotate) var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia); margin: 0px 0px 0px -0.125rem; font-size: 3rem; font-weight: 900; font-family: SB, MBP, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans; line-height: 1; text-transform: uppercase; letter-spacing: -0.05em; --tw-text-opacity: 1; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: left; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
            FROM THE ALLEY<br style="box-sizing: border-box; border-width: 0px; border-style: solid; border-color: rgba(229,229,229,var(--tw-border-opacity)); border-image: initial; --tw-translate-x:0; --tw-translate-y:0; --tw-rotate:0; --tw-skew-x:0; --tw-skew-y:0; --tw-scale-x:1; --tw-scale-y:1; --tw-transform:translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); --tw-border-opacity:1; --tw-ring-inset:var(--tw-empty, ); --tw-ring-offset-width:0px; --tw-ring-offset-color:#fff; --tw-ring-color:rgba(59,130,246,0.5); --tw-ring-offset-shadow:0 0 transparent; --tw-ring-shadow:0 0 transparent; --tw-shadow:0 0 transparent; --tw-blur:var(--tw-empty, ); --tw-brightness:var(--tw-empty, ); --tw-contrast:var(--tw-empty, ); --tw-grayscale:var(--tw-empty, ); --tw-hue-rotate:var(--tw-empty, ); --tw-invert:var(--tw-empty, ); --tw-saturate:var(--tw-empty, ); --tw-sepia:var(--tw-empty, ); --tw-drop-shadow:var(--tw-empty, ); --tw-filter:var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow); --tw-backdrop-blur:var(--tw-empty, ); --tw-backdrop-brightness:var(--tw-empty, ); --tw-backdrop-contrast:var(--tw-empty, ); --tw-backdrop-grayscale:var(--tw-empty, ); --tw-backdrop-hue-rotate:var(--tw-empty, ); --tw-backdrop-invert:var(--tw-empty, ); --tw-backdrop-opacity:var(--tw-empty, ); --tw-backdrop-saturate:var(--tw-empty, ); --tw-backdrop-sepia:var(--tw-empty, ); --tw-backdrop-filter:var(--tw-backdrop-blur) var(--tw-backdrop-brightness) var(--tw-backdrop-contrast) var(--tw-backdrop-grayscale) var(--tw-backdrop-hue-rotate) var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia);" />
            TO THE GARDEN</h1>
            </div>
            <hr style="width:93%;margin-left:3%" />
            <div style="padding: 30px">
                
        <p style=" font-family: 'Courier New', Courier, monospace; text-align: left; font-weight: bolder;">Azuki is a brand. </p>
        <p style=" font-family: 'Courier New', Courier, monospace; text-align: left; font-weight: bolder;">A new kind of brand that we build together. </p>
        <p style=" font-family: 'Courier New', Courier, monospace; text-align: left; font-style: normal; font-weight: bolder; color: #C2283A; font-size: x-large;">A brand for the metaverse. By the community. </p>
        <p style=" font-family: 'Courier New', Courier, monospace; text-align: left;font-weight: bolder;">A collection of 100 avatars that give you membership access to The Garden. It starts with exclusive streetwear collabs, NFT drops, live events, and much more that will be revealed over time. Community ownership in Azuki allows for a new genre of media which the world has yet to explore. An Azuki is your identity in the metaverse — let&#39;s build together. </p>
        <p style=" font-family: 'Courier New', Courier, monospace; text-align: left;font-weight: bolder;">The Garden is a corner of the internet where art, community, and culture fuse to create magic. The lines between the physical and digital worlds are blurring and the rules are being rewritten. </p>
        <p style=" font-family: 'Courier New', Courier, monospace; text-align: left;font-weight: bolder;">Take the Red Bean.</p>
        </div>
            </div>
        <asp:Button ID="Button1" runat="server" Text="Login" CssClass="button1" OnClick="Button1_Click" style="margin:50px;border-radius:15px;font-size:large;" Height="100px" Width="40%"/>
        <asp:Button ID="Button2" runat="server" Text="Sign Up" CssClass="button1" OnClick="Button2_Click" style="margin:50px;border-radius:15px;font-size:large;" Height="100px" Width="40%"/>
    </div>

   



</asp:Content>
